language: node_js
node_js: "9"
branches:
  only:
  - master
  except:
  - 1.0.x
after_success:
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
deploy:
  provider: heroku
  api_key:
    secure: B9+Mh83CRFXJR3mkRh9TgMUv8PepJzZiWzDRtpmX79UGsepw52SIlJGsxSrpDDTXYxYPxNrxLCJAnR663NV5KtJJIJ2ntFOSdRl2zulXyBlj0K8NHJ7ZithXuUNnNruRNUA0UZEQyAZNnVatT7YhcmBC4I14u45mtvCV6DFzkEmFKUQe+rv9u49RXaL1Igon6u/AXMd+gum+PK1dPYwo6/eZb3ojw6WT1h3a9+TQ6tinLc7qUCzupub1CW0GBKkk745OQS/oWSyMOiFLoWOvG7G4T9F/h8h3fcJuIzATrhPZXhPQB65nN7T/tApxYRaquQKzZebcPleTehQh0hu9vQCkw9Z6E0tjkGA189CcAN3FAKSLRXKZ82Fu+Oh8qdPlh4QMU+UYEwrBRrFiiujYYAc/BZvJVl5ZhsVICtIHzYciqo4jamojGu+knpDfD1UirHDFbpI4tqL2pHShpxAID/KX6VeLlmUuxKGJKc1dipFfyDjGuQKI5CconsFJqxJDcfxyB/ujPaOAMMKmlEq72wEtvMY4bwzkl5mVfOmdUzSzjG9wQcaeCGfIHm6BD1VyL190s56sUT+MNHcitQTaAGFub+NV0DbiciH1WiXDJkmbSoWrIJtEyniOeUmAd86JSMnAdeyx+EPPHt/JqAngGjncUJPJVWRBagvIN+ZtHIk=
  app: todo-node-express
  on:
    repo: ivandzf/todo-api
notifications:
  slack:
    secure: Rk0+55I63VaFmq/8mmtbDhZyClJ5diLZLS4xxMNfRY4b2JTa+xfvymBizeUuBnSmcTFVpeHIM98dvh2NdTk4PW+ZTFNXfkHEA1/mOSlogqENB5sN5+QIZDD1xk4eol2ulLlEgzxuunHL/qFhzSBWXX/CVb4b7cB6fscnFtwZq+ETDLoKg+coAUTdEVc9bGQl4DjjBiY49qSOdXmiFeyJzYOwyeeBteQoukh7Z7Vt8wxhFDq7EMg9U+9tNSPgOvjTV+Pw3S4r0vQHZAgCHowaLAcyzgGrrxxXwNsGN0StHRXUd6eoXD2jvNbLRFbn1sHqdPRpOjU+kcb3qDk8fiftlsjmsr2lg80T+4KpFfTHrGJyQxz0Pk/LWqy2dX5uQU9qB+fxB3gaIIrL969JIRQsS1GGLHVbOEjQMs6wZQBm+wFaNu+h25L3RW8Cf+Yxm4VhwfpJxpX8N5WeqHsvjKa/hC3v+wwDf8R5ZV0l4exT5PPOabyfJ6jnI6nasZf1nt+kfw5mPW61Jo20B4O/ziPzk6o1LyIrY+WhD3CuxH0wscOcja8Eea+pZHh9GL90wkpHZyhs7dqQO46CSzy++XxYivz7eabDr8Gnd9jSZXULdGuTB7sPuq5eaCtaspBIt3fd4Qvn3/z4O6wn9zExE4XYM9r9HBDeTRKNIP3TVXBZDE4=
